### ISSUE TITLE
Crashing when selecting Email app for Icon Request 

### ISSUE THREAD

**Issue by randomvector** [danimahardhika/candybar-library#83]
Since the update to 3.3.0 (I am using 3.3.0 even though the crash reports CandyBar Version : 3.2.2) I'm getting full app crashes when selecting an email app (Gmail) for sending the icon request. I pasted the crashlogs sent from two devices:

Manufacturer : LGE
Model : Nexus 4
Product : nitrogen_mako
Screen Resolution : 768 x 1184 pixels
Android Version : 7.1.2
App Version : 0.9
CandyBar Version : 3.2.2
Crash Time : 2017-08-08 03:55:20
Class Name : java.lang.NullPointerException
Caused By : java.lang.NullPointerException: Attempt to invoke virtual method 'void me.zhanghai.android.materialprogressbar.MaterialProgressBar.setVisibility(int)' on a null object reference

com.dm.material.dashboard.candybar.adapters.IntentAdapter.lambda$getView$2(IntentAdapter.java:118)
com.dm.material.dashboard.candybar.adapters.IntentAdapter$$Lambda$1.onClick(Unknown Source)
android.view.View.performClick(View.java:5637)
android.view.View$PerformClick.run(View.java:22429)
android.os.Handler.handleCallback(Handler.java:751)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6178)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

Manufacturer : OnePlus
Model : ONE A2003
Product : OnePlus2
Screen Resolution : 1080 x 1920 pixels
Android Version : 7.1.2
App Version : 0.9
CandyBar Version : 3.2.2
Crash Time : 2017-08-08 04:02:19
Class Name : java.lang.NullPointerException
Caused By : java.lang.NullPointerException: Attempt to invoke virtual method 'void me.zhanghai.android.materialprogressbar.MaterialProgressBar.setVisibility(int)' on a null object reference

com.dm.material.dashboard.candybar.a.k.a(SourceFile:118)
com.dm.material.dashboard.candybar.a.l.onClick(Unknown Source)
android.view.View.performClick(View.java:5657)
android.view.View$PerformClick.run(View.java:22453)
android.os.Handler.handleCallback(Handler.java:751)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:154)
android.app.ActivityThread.main(ActivityThread.java:6236)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by danimahardhika** [comment]
@randomvector Again it's working just fine on my side? Did the crash happened on your own device? If yes try to clean project, the build apk again.

**Comment by randomvector** [comment]
Yes the crash occurred on my own device that I just use for development. I tried it on my personal device and the crash still happened. I tried cleaning and rebuilding the project and the same issue. Does the crash log give any indication what's causing the crash?

**Comment by danimahardhika** [comment]
Try to open your project, delete **builds** folder. Open **app** folder, delete **builds** folder again. After that try to run the app again.

**Comment by randomvector** [comment]
Hi I tried deleting the build folders as requested but crash still occurs when selecting email client. I tried the app on a fresh avd build and same issue. I have included the crashlog below:

Manufacturer : unknown
Model : Android SDK built for x86
Product : sdk_google_phone_x86
Screen Resolution : 1080 x 1776 pixels
Android Version : 6.0
App Version : 0.9
CandyBar Version : 3.2.2
Crash Time : 2017-08-08 11:35:28
Class Name : java.lang.NullPointerException
Caused By : java.lang.NullPointerException: Attempt to invoke virtual method 'void me.zhanghai.android.materialprogressbar.MaterialProgressBar.setVisibility(int)' on a null object reference

com.dm.material.dashboard.candybar.adapters.IntentAdapter.lambda$getView$2(IntentAdapter.java:118)
com.dm.material.dashboard.candybar.adapters.IntentAdapter$$Lambda$1.onClick(Unknown Source)
android.view.View.performClick(View.java:5198)
android.view.View$PerformClick.run(View.java:21147)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5417)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by danimahardhika** [comment]
This crash is strange, it's like the project not compiled properly.

**Comment by randomvector** [comment]
Yes, I am unsure how to proceed. I have checked the SDK and Java runtime to make sure they are up to date. At the moment I have rolled back to 3.2.2 as it's stable for me and I'm nearing my app release so am focused on that.

**Comment by danimahardhika** [comment]
This error turns out because of compilation error from Android Studio.

**Comment by randomvector** [comment]
Do you recommend reinstalling Android Studio?

**Comment by danimahardhika** [comment]
No, try to invalidates cache (File - Invalidates ...), clean project, reimport project, or even try to start again from beginning.

**Comment by randomvector** [comment]
I managed to fix the crash. The issue was that I had imported too many files from the master in the layout folder and that was causing the email selector to crash when pressed. I just used the layout files I changed and all was fine when updating to 3.3.2.
